services:

  # REVERSE PROXY
  ## Traefik reverse proxy and load balancer
  reverse-proxy:
    image: traefik:2.9.8
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # APPLICATIONS

  election-management:
    extends:
      file: common.yml
      service: quarkus
    build:
      context: ./election-management
      dockerfile: src/main/docker/Dockerfile.jvm
    image: dio/election-management:${TAG:-1.0.0}
    depends_on:
      - database
      - caching
    labels:
      - traefik.http.routers.election-management.rule=Host(`vote.dio.localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.election-management.entrypoints=web

  voting-app:
    extends:
      file: common.yml
      service: quarkus
    build:
      context: ./voting-app
      dockerfile: src/main/docker/Dockerfile.jvm
    image: dio/voting-app:${TAG:-1.0.0}
    depends_on:
      - database
      - caching
    labels:
      - traefik.http.routers.voting-app.rule=Host(`vote.dio.localhost`) && PathPrefix(`/api/voting`)
      - traefik.http.routers.voting-app.entrypoints=web

  result-app:
    extends:
      file: common.yml
      service: quarkus
    build:
      context: ./result-app
      dockerfile: src/main/docker/Dockerfile.jvm
    image: dio/result-app:${TAG:-1.0.0}
    depends_on:
      - database
      - caching
    labels:
      - traefik.http.routers.result-app.rule=Host(`vote.dio.localhost`) && Path(`/`)
      - traefik.http.routers.result-app.entrypoints=web

  # DATABASE - MariaDB relational database
  database:
    image: mariadb:10.11.2
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-root}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-election}
    volumes:
      - mariadb_data:/var/lib/mysql

  # CACHING - Redis in-memory cache
  caching:
    image: redis:7.0.9
    volumes:
      - redis_data:/data

  # LOGGING - Centralized logging pipeline
  mongodb:
    image: mongo:6.0.4
    volumes:
      - mongodb_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:2.6.0
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - action.auto_create_index=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.disabled=${OPENSEARCH_SECURITY_DISABLED:-true}
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  graylog:
    image: graylog/graylog:5.0.5
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: "${GRAYLOG_HTTP_EXTERNAL_URI:-http://localhost:9000/}"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:-forpasswordencryption_secret_16chars}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:-8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    depends_on:
      opensearch:
        condition: service_started
      mongodb:
        condition: service_started
    labels:
      - traefik.enable=true
      - traefik.http.routers.graylog.rule=Host(`logging.private.dio.localhost`)
      - traefik.http.routers.graylog.entrypoints=web
      - traefik.http.routers.graylog.service=graylog
      - traefik.http.services.graylog.loadbalancer.server.port=9000

  # OPENTELEMETRY - Tracing collector
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.admin-admin-auth.basicauth.users=${JAEGER_BASICAUTH_USERS:-admin:$$2y$$05$$B3PS97vYDsx6Hk4e/F8bSOGdB2uq.oabTU7SbMdjJKxdAeKKI8pTO}
      - traefik.http.routers.jaeger.rule=Host(`telemetry.private.dio.localhost`)
      - traefik.http.routers.jaeger.entrypoints=web
      - traefik.http.routers.jaeger.service=jaeger
      - traefik.http.routers.jaeger.middlewares=admin-admin-auth@docker
      - traefik.http.services.jaeger.loadbalancer.server.port=16686

volumes:
  mariadb_data:
  redis_data:
  mongodb_data:
  opensearch_data:
