quarkus.application.name=result-app
quarkus.shutdown.timeout=5S

# LOGGING
%prod.quarkus.log.handler.gelf.enabled=${QUARKUS_LOG_GELF_ENABLED:true}
%prod.quarkus.log.handler.gelf.host=${QUARKUS_LOG_HANDLER_GELF_HOST:graylog}
%prod.quarkus.log.handler.gelf.port=${QUARKUS_LOG_HANDLER_GELF_PORT:12201}
%prod.quarkus.log.handler.gelf.additional-field."app".value=${quarkus.application.name}
%prod.quarkus.log.handler.gelf.include-full-mdc=true
%prod.quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

# OPENTELEMETRY
%prod.quarkus.opentelemetry.enabled=${QUARKUS_OPENTELEMETRY_ENABLED:true}
%dev.quarkus.opentelemetry.enabled=false
quarkus.opentelemetry.tracer.exporter.otlp.endpoint=${QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT:http://jaeger:4317}
